"""
Base exceptions
"""


class AwsToolsException(Exception):
    """
Base class for exceptions generated by the library
"""
    pass


class ConfigurationError(AwsToolsException):
    """
Raised when something is misconfigured
"""
    pass
